### ISSUE TITLE
JetStream support

### ISSUE THREAD

**Issue by danieleteti** [paolo-rossi/nats.delphi#2]
Hi @paolo-rossi , thanks for this nice library.
Do you have any plans about JetStream support?
I'm evaluating some messaging-oriented-middleware for a new project and NATS is really good for our needs (simple and powerful), but we really need At-Least-Once QoS (At-Most-Once isn't enough).

**Comment by paolo-rossi** [comment]
Hey @danieleteti !

> Do you have any plans about JetStream support?
Yes definitely.

> I'm evaluating some messaging-oriented-middleware for a new project and NATS is really good for our needs (simple and powerful), but we really need At-Least-Once QoS (At-Most-Once isn't enough).

I do too have some cases where it makes sense to use "At-Least-Once" or even "Exactly-Once" levels so I have already pressure to implement JetStream support!
However I don't have a specific deadline, but I think I will be able to start working on this feature in the next months... usually holidays are perfect to do this so, finger crossed, in the coming Christmas holidays I hope to do some work on that! :-)

Ciao,
Paolo.

**Comment by danieleteti** [comment]
Thanks a lot Paolo, I'm looking forward to see your job on JetStream support.

Ciao, a presto.
